name: Publish APT repository

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dpkg tools
        run: sudo apt update && sudo apt install -y apt-utils dpkg-dev

      - name: Build Packages metadata
        run: |
          echo "Generating Packages for arm64..."
          dpkg-scanpackages --multiversion pool/main override /dev/null \
            | grep -A9999 '^Package:' \
            | awk '/Architecture: arm64/{p=1} p{print} /^$/{p=0}' \
            > "dists/stable/main/binary-arm64/Packages"
          gzip -kf "dists/stable/main/binary-arm64/Packages"

          echo "Generating Packages for amd64..."
          dpkg-scanpackages --multiversion pool/main override /dev/null \
            | grep -A9999 '^Package:' \
            | awk '/Architecture: amd64/{p=1} p{print} /^$/{p=0}' \
            > "dists/stable/main/binary-amd64/Packages"
          gzip -kf "dists/stable/main/binary-amd64/Packages"

          apt-ftparchive -c release.conf release dists/stable > dists/stable/Release

      - name: Upload Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


  test:
    name: APT smoke test
    needs: deploy
    runs-on: ubuntu-24.04
    container:
      image: debian:13.3

    steps:
    - name: Install prerequisites
      run: apt update && apt install -y ca-certificates curl gnupg

    - name: Add APT repository
      run: |
        echo "deb [trusted=yes] https://hoefling.io/apt stable main" \
          > /etc/apt/sources.list.d/personal.list

    - name: Update APT
      run: apt update

    - name: Install package
      run: apt install -y python3-magic-filter
